#define ffmpeg_video_ingest_available ffmpeg_video_ingest_available_hls_embedded
#define ingest_video_ffmpeg_direct ingest_video_ffmpeg_hls_embedded_direct
#include "ffmpeg_ingest_hls.cpp"
#undef ingest_video_ffmpeg_direct
#undef ffmpeg_video_ingest_available
